applications:
  universal:
    component: simpleWebHookIntegration
    name: Universal Webhook
    description: "Use this app for simple generic webhooks integrations. Once configured it will post messages received through the webhook into Symphony. It can be configured to post in a 1:1 chat with you or in a chat room with other Symphony users."
    publisher: Symphony
    context: universal
    keystore:
      password: ${KEYSTORE_PASS}
